### PR TITLE
Sanitize class name

### PR DESCRIPTION
**Pull request by ivebe**
PR for issue #116

### CODE REVIEW

**Comment by ReeceM** [comment]
@ivebe, could you add the .phpunit results cache file to the gitignore file. 

It will be better for future additions when running the tests 👍

**Comment by ivebe** [comment]
Done.

**Review by Qoraiche — APPROVED** [review]
LGTM 👍

**Review by ReeceM — APPROVED** [review]
Looks alright 👍 

And thank you for adding a unit test

**Comment by ReeceM** [comment]
@Qoraiche just want to check, should this be a feature release on the v3 branch only? Or on both the v3 and v2 one?

**Comment by Qoraiche** [comment]
@ReeceM hum, I think we can keep it only for the v3

**Comment by ReeceM** [comment]
@Qoraiche cool.

**Pull request merged**
