### PR TITLE
move away from db and store meta data in a json file

### PR DESCRIPTION
**Pull request by griffins**
instead of storing the data in a database, we now store the data in ```templates.json``` file in the ```mail_dir``` directory which defaults to ```app/Mail/templates.json```

### CODE REVIEW

**Comment by dstollie** [comment]
I was playing around with this package and I love the idea of being able to update emailables without program them all by hand. This way our marketing team can update the mailables by themselves. 

In all our applications we try to avoid having to "commit/push" code from the production application. We generally only pull code on production. If this package follows the path this PR is pushing it. There is no way to use this package without committing/pushing code from the server itself. I think this potentially could put off people to use this package.

I understand that it it not really usefull to do everything in the database. A "Mailable" class is supposed to be dynamic and it would make alot of sense to replace this part with a database counterpart. But storing the contents of a template would make sense in my opinion. Spatie for example created a package to store the email templates in the database https://github.com/spatie/laravel-database-mail-templates.

For us it would make more sense to store the templates in the database since those things would be updated pretty regularly by people who are not developers. The Mailable on the other hand always have to be implemented. An option to disable the creation of Mailables in production is an option than. This way this package can work without having to update the codebase of the app.

I'm curious in what you guys think about this subject.

**Comment by griffins** [comment]
Hi, if you looked at the source code, what this does is managing the mails as part of the source code. The only information that was stored in the database was the metadata, from the schema shown below.

```php
 Schema::create('maileclipse_templates', function (Blueprint $table) {
            $table->increments('id');
            $table->string('template_name')->unique();
            $table->string('template_slug')->unique();
            $table->string('template_type')->default('markdown');
            $table->string('template_view_name');
            $table->string('template_skeleton');
            $table->string('template_description')->nullable();
 });
```

As you can see that has nothing to do with the actual email, which has to be coded still since they are actual laravel or markdown templates. 

So as of now the emails have to be created from a development machine and deployed as source code

**Comment by dstollie** [comment]
@griffins Thanks for mentioning and the whole reason I started this discussion is to talk about the descission to put the templates content in the source code. The whole reason we would use an application like this is to enable our marketing team to create templates themselves on our production environment. Pushing code changes to to git from our production environment is not really something that we like to do. 

The reason I started this discussion is to understand which path this package goes. By accepting this PR the authors of this package say: "In the near future we are not going to manage our templates in the database which means you should git commit/push in your production environment." For us this would be a big con and not a fitting solution for us

**Comment by neoighodaro** [comment]
I think the way the package is built, it's not flexible enough. It should be. You should be able to switch storage providers and thus allow people store things wherever they want or at least make their own implementations and register those. That is what should be fixed, not another concrete implementation like database or any storage at all.

**Comment by griffins** [comment]
Hi
@neoighodaro I believe allowing devs to configure this option would be the best way forward. That way we would make everyone happy. In case everyone wants this we can allow that flexibility by using providers.

**Comment by Qoraiche** [comment]
Hi @griffins thanks for your PR, I will accept this PR until we find something better can work for everyone, Now at least we should make it work on the production environment.

**Comment by Qoraiche** [comment]
Hello again @griffins,

I found that this PR produce an error when trying to edit template Details!

Reproduce:
- create template
- edit template details
- submit changes

XHR error response message:
`message | Method Illuminate\Support\Collection::add does not exist.`

file | qoraiche/mailEclipse/src/mailEclipse.php
-- | --
line | 125
class | Illuminate\Support\Collection

it would be great if you can fix this issue and Open a new PR.

**Pull request merged**
