### PR TITLE
Fixed and working with L6

### PR DESCRIPTION
**Pull request by codepotato**
Updated as per your comments and fully tested on L6.

### CODE REVIEW

**Comment by codepotato** [comment]
With tonnes of help from @sammyjo20 too!

**Comment by codepotato** [comment]
@Qoraiche apologies for all the commits and package names changes, was testing locally and didn't realise you would get notified every time. 

Working nicely now!

**Comment by Qoraiche** [comment]
@codepotato thank you, let's wait for @ReeceM review!

**Comment by ReeceM** [comment]
@codepotato and @Qoraiche, Just checking it :), will run it locally.

Noticed one thing so far, it won't be backwards compatible, unless Qorachie, you would like to merge this with a new branch version and make it specific to Laravel v6.

If not, Gareth, could you make it require the packages like so:

 `"illuminate/support": "~5|~6"`
`"phpunit/phpunit": "~7.0|~8.0"`
`"orchestra/testbench": "~3.0|~4.0"`

**Comment by codepotato** [comment]
I'll update that now @ReeceM @Qoraiche

**Comment by Qoraiche** [comment]
Good catch @ReeceM

**Comment by codepotato** [comment]
Done :)

**Comment by Qoraiche** [comment]
@codepotato it would be great if you test backward compatibility on both versions to confirm @ReeceM suggestion.

**Comment by codepotato** [comment]
@Qoraiche Did I not already do this?

**Comment by ReeceM** [comment]
> @Qoraiche Did I not already do this?

I think you were both quick on the keyboard :)

**Comment by Qoraiche** [comment]
oh didn't notice, I thought you just confirm that it's working only on laravel 6

**Comment by codepotato** [comment]
Apologies, I pushed up a new commit with the updated composer dependencies :)

**Comment by Qoraiche** [comment]
@codepotato it would be even greater if you could update readme to get those changes (if needed).

**Pull request merged**
