### PR TITLE
Support only Laravel v8

### PR DESCRIPTION
**Pull request by ReeceM**
Use only version 8 in the composer file and support to prevent duplicate class issues for the legacy factories.

This would require a new major version release, `v3.x` But would then also remove the support of the version `v2` branches, as the other apps would not function properly. 

This could be split into a new v2 branch for the older versions of Laravel.

The reason this is being done would be to remove the following: 
```bash
Warning: Ambiguous class resolution, "Illuminate\Database\Eloquent\Factory" was found 2x: in ".../vendor/laravel/legacy-factories/src/Factory.php" and ".../vendor/laravel/framework/src/Illuminate/Database/Eloquent/Factory.php", the first will be used.
Warning: Ambiguous class resolution, "Illuminate\Database\Eloquent\FactoryBuilder" was found 2x: in ".../vendor/laravel/legacy-factories/src/FactoryBuilder.php" and ".../vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php", the first will be used.
Warning: Ambiguous class resolution, "Illuminate\Support\Traits\Macroable" was found 2x: in ".../vendor/illuminate/macroable/Traits/Macroable.php" and ".../vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php", the first will be used.
```

### CODE REVIEW

**Comment by Qoraiche** [comment]
@ReeceM Hummm, i think you right! could you check this commit from spatie please :
https://github.com/spatie/laravel-activitylog/commit/450adecfd2e1a5766d77ba9867937928d4c91955#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by ReeceM** [comment]
@Qoraiche Thanks for sharing the link to the commit on the file 👍 

----

I am thinking this may require doing the following to make this practical:

- `master` branch will be for `v3.x` currently and support Laravel 8 issues and updates
- `v2.x` branch will support `v2.x` and all the Laravel 5, 6, 7 versions. 

`v2.1.0` will have to be reverted to a `v2.1.1` release and drop support for Laravel 8 so as not to cause issues for other users who get a duplicate namespace warning. 

Also if we can support Laravel 8 directly on a single branch we can make adjustments to handle the new Factory class style on the models.

**Comment by ReeceM** [comment]
Hi @Qoraiche, wanting to check with you if removing the `composer.lock` file from version control would bring the package more inline with the rest of the PHP packages at the current time?

Composer does suggest that the file is not needed for libraries as it will not be used when used in other packages.

https://getcomposer.org/doc/02-libraries.md#lock-file

I am looking at removing it in both the v3 and v2 changes so it is neater.

**Comment by Qoraiche** [comment]
> Hi @Qoraiche, wanting to check with you if removing the `composer.lock` file from version control would bring the package more inline with the rest of the PHP packages at the current time?
> 
> Composer does suggest that the file is not needed for libraries as it will not be used when used in other packages.
> 
> https://getcomposer.org/doc/02-libraries.md#lock-file
> 
> I am looking at removing it in both the v3 and v2 changes so it is neater.

Hi @ReeceM, you right! apparently we can remove it and gitignore it as the doc says

Thanks!

**Comment by ReeceM** [comment]
👍 awesome :)

**Pull request merged**
