### PR TITLE
To fix issue #32

### PR DESCRIPTION
**Pull request by griffins**
use ```array_merge``` instead of laravel collection ```add``` method for backward compatibility

### CODE REVIEW

**Comment by Qoraiche** [comment]
Hello @griffins,

Template Details Saved correctly but can't access templates page (`maileclipse/templates`).

Error message:
`Trying to get property 'template_slug' of non-object (View: **/qoraiche/mailEclipse/resources/views/sections/templates.blade.php)`

Laravel Version:
**5.7.28**

**Comment by griffins** [comment]
Hi, I tried to reproduce the error but was not able to, everything seems to work correctly. 

Maybe you should check your ```app/Mail/templates.json``` for any errors.

**Comment by Qoraiche** [comment]
@griffins, to reproduce:

1. clean your templates.json (`{}`)
2. add new template using ui.
3. update template details.
4. access templates page

**Comment by griffins** [comment]
@Qoraiche thanks for that, I was able to track down the error and pushed a patch

**Comment by Qoraiche** [comment]
@griffins Thank You!

**Pull request merged**
