### PR TITLE
fix: compatible way to call the method on mailable

### PR DESCRIPTION
**Pull request by ReeceM**
## Description

Adds a method exists check to the function of the buildMailable data method to check which method exists on the Mailable. 

## Related Issue

#218 

## Motivation and Context

This is to make the preview functionality work with Laravel 9

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by ReeceM** [comment]
Render works in some contexts then. I didn't get that error but does make sense as the returned value gets used later in to get the view data etc.

I'll have to have another look in a few hours though at the moment 👍

**Comment by Qoraiche** [comment]
> The `render` method seems to be the same functionally to the old `build` one.
> 
> I tested the fix locally, not sure if we can do a require on composer with the branch number

we can use the render method to return the mailable preview

**Comment by ReeceM** [comment]
Note:

Lines 553 - 557 needs to change in the MailEclipse class as the mailables won't display after the fix works for Laravel 9

```diff

            $collection = collect($fqcns)->map(function ($mailable) {
                return $mailable;
-            })->reject(function ($object) {
-               return ! method_exists($object['namespace'], 'build');
-            });
```

**Comment by ReeceM** [comment]
Currently working when there aren't things in the Mailables constructor. As when it is instanciated using the content method / render method it actually returns a model that doesn't have `viewData` props.

**Comment by Qoraiche** [comment]
Thanks for the changes @ReeceM, I'll give it a try tonight and get back to you

**Comment by ReeceM** [comment]
Thank you 👍

I suspect it will need some more work to get it working nicely.

**Comment by Qoraiche** [comment]
> Thank you 👍
> 
> I suspect it will need some more work to get it working nicely.

Indeed, is it safe to push these changes as a quick fix for laravel 9?

**Comment by ReeceM** [comment]
> > Thank you 👍
> 
> > 
> 
> > I suspect it will need some more work to get it working nicely.
> 
> 
> 
> Indeed, it looks good to me, is it safe to push these changes as a quick fix for laravel 9?

The changes are alright for Laravel 9 it shouldn't be breaking it further than it is at the moment because of the change in the Mailable methods. 

What might happen is the edge cases will be found for some who have a different setup. 

I did try and run it using an old mailable made with the build method and one made using the new style in a Laravel 9 app and both worked.

**Review by Qoraiche — APPROVED** [review]
All good, it can be merged @ReeceM (y)

**Comment by Qoraiche** [comment]
I'm going to open a new PR to support to make MailEclipse work with SymfonyMail after SwiftMailer was removed

**Comment by ReeceM** [comment]
> I'm going to open a new PR to make MailEclipse work with SymfonyMail after SwiftMailer was removed

Okay cool 💯 I'll merge this and tag it

**Pull request merged**
