### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-mail-editor.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "qoraiche/laravel-mail-editor": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by ReeceM** [comment]
Hey @Qoraiche, 

I will have a look this evening, thanks for pinging 👍 Will this be tagged as `v4`? As it is only targeting Laravel 9?

But it does look alright (I just need to bump the mocker lib to add 9.0 support.)

**Comment by jasonmccreary** [comment]
@ReeceM, yes, this automation analyzes your current `composer.json` and determines if you supported multiple older version. If so it appends. Otherwise, it bumps you to the latest.

**Comment by ReeceM** [comment]
Thanks @jasonmccreary  for the clarification on the action taken by the shift 👍 

@Qoraiche Looks alright and also bumped Mocker to support Laravel 9 💯

**Review by ReeceM — APPROVED** [review]

**Comment by ReeceM** [comment]
> > Hey @Qoraiche,
> > I will have a look this evening, thanks for pinging 👍 Will this be tagged as `v4`? As it is only targeting Laravel 9?
> > But it does look alright (I just need to bump the mocker lib to add 9.0 support.)
> 
> But I guess this PR should bump both 8 and 9? as we don't have any breakable changes for 9? then we can simply create a minor release for it

That sounds like a good idea then 👍

**Review by Qoraiche — APPROVED** [review]

**Pull request merged**
