### PR TITLE
allow user to configure mail view directory and namespace

### PR DESCRIPTION
**Pull request by griffins**
This PR aims to allow the user to configure the mail dir and namespace. If possible we should also replace saving database metadata to a JSON file so that they can be persisted as part of the source code. 
Sorry about the code formatting that made the commit appear to have changed many files

### CODE REVIEW

**Comment by Qoraiche** [comment]
Hi @griffins, sorry for being late, also thanks for this PR

The concept looks good but I think it needs more than that! also, I found that there are a lot of problems with this PR:

1. Templates created in the application public folder when updating a template.
2. Templates not updated in the edit template section.
3. Template View label not updated as well `namespace::dir.template` e.g `maileclipse::templates.invoice`.
4. PR code formatting makes it really hard to know what code lines are exactly modified.

**Comment by griffins** [comment]
Hi, ive confirmed problem number 1 and i have released an update to the PR, Fixing it also fixed problem 2.

**Comment by griffins** [comment]
@Qoraiche did you get time to look at this again?

**Comment by Qoraiche** [comment]
Hi @griffins sorry for late i'm very busy this week,

Your PR works fine, but i found out that a lot of users wants to store templates in a database instead of modify template files directly to avoid vcs problems, it would be great if you can PR this!

**Comment by griffins** [comment]
Okay, I suggest I enhance this PR to make everyone happy. Am thinking of making this a configurable option. As i understand the actual template is store on the file system. We need to define this cleary so that i can get what am supposed to do.

**Comment by Qoraiche** [comment]
No plans to merge

**Pull request closed without merging**
